Hellomicroverse
Mucyosoda/Hello-Microverse pull request #2
Opened 2021-08-10 14:11 UTC by Mucyosoda

2021-08-10 14:47 UTC, Mucyosoda commented
added different files like test.md, index.html, style.css, gitignore file and linters.yml

2021-08-10 14:53 UTC, AshakaE requested changes
### Hi @Mucyosoda  🙋‍♀️, 

Good job so far! 👌
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


#  Required Changes ♻️ 🚧
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 14:53 UTC, AshakaE commented on test.md
> +"This file should be ignored by git"
- [ ] Please make sure this file is properly ignored from git before making a `git push`

2021-08-10 17:49 UTC, emmanuellekamwa requested changes
**STATUS: CHANGES REQUESTED 🛠🛑**
Hello @Mucyosoda 👋🏽
Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._👀👇🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-10 17:49 UTC, emmanuellekamwa commented on .gitignore
> +test.md
As said by the previous TSE the test.md file should be ignored but I am still seeing it amongst your files. Please fix that.

2021-08-10 17:49 UTC, emmanuellekamwa commented on README.md
> +
Your screenshot is breaking. Please also try and fix that.

2021-08-11 09:01 UTC, dasileker approved these changes
### **Hi @Mucyosoda,** 

### **Project Approved✅**

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### **Optional Suggestion**

- Please take the TSE notes, your PR doesn't have a descriptive PR, next project add description to your PR  see 👇
![pr](https://user-images.githubusercontent.com/61562626/129000966-ecd1ea6b-ebca-401f-ba5c-ea937fffe0d3.jpeg)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-11 10:13 UTC, merged